-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 23:33:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FlaskToDo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FlaskToDo` DEFAULT CHARACTER SET utf8 ;
USE `FlaskToDo` ;

-- -----------------------------------------------------
-- Table `FlaskToDo`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlaskToDo`.`Usuario` (
  `id_Usuario` INT NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_Usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FlaskToDo`.`Tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlaskToDo`.`Tarefa` (
  `id_Tarefa` INT NOT NULL,
  `Descricao` VARCHAR(500) NOT NULL,
  `Ativo` BINARY NOT NULL,
  `id_Usuario` INT NOT NULL,
  PRIMARY KEY (`id_Tarefa`),
  INDEX `fk_Tarefa_Usuario_copy1_idx` (`id_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Tarefa_Usuario_copy1`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `FlaskToDo`.`Usuario` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
